version: '3.8'

services:
  mysql:
    image: mysql:9.4.0
    env_file:
      - path: ./apps/backend/.env
        required: true
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  mongo:
    image: mongo:6.0.26
    env_file:
      - path: ./apps/backend/.env
        required: true
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    env_file:
      - path: ./apps/backend/.env
        required: true
    environment:
      MINIO_ROOT_USER: ${MINIO_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

  backend:
    build:
      context: ./
      dockerfile: ./apps/backend/Dockerfile
    env_file:
      - path: ./apps/backend/.env
        required: true
    environment:
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MINIO_HOST: minio
      MINIO_PORT: 9000
      MINIO_USERNAME: ${MINIO_USERNAME}
      MINIO_PASSWORD: ${MINIO_PASSWORD}
      MINIO_BUCKET: ${MINIO_BUCKET}
    ports:
      - "3001:3001"
    depends_on:
      - mysql
      - mongo
      - minio
    restart: unless-stopped

volumes:
  mysql_data:
  mongo_data:
  minio_data:
